import Foundation
import SwiftUI
import UniformTypeIdentifiers

struct SearchResult: Identifiable, Hashable, Sendable {
    var id: String { path }
    let url: URL
    let name: String
    let path: String
    let kind: ResultKind
    let size: Int64?
    let modifiedDate: Date?
    let relevanceScore: Double
    let subtitle: String

    var displayName: String { name }
    var parentPath: String { url.deletingLastPathComponent().path }

    init(url: URL, name: String, path: String, kind: ResultKind, size: Int64?, modifiedDate: Date?, relevanceScore: Double, subtitle: String = "") {
        self.url = url
        self.name = name
        self.path = path
        self.kind = kind
        self.size = size
        self.modifiedDate = modifiedDate
        self.relevanceScore = relevanceScore
        self.subtitle = subtitle
    }

    enum ResultKind: String, Sendable {
        case file
        case folder
        case application
        case image
        case video
        case audio
        case document
        case archive
        case code
    }

    static func kind(from url: URL) -> ResultKind {
        let ext = url.pathExtension.lowercased()
        let filename = url.lastPathComponent

        if ext == "app" { return .application }
        if ["png", "jpg", "jpeg", "gif", "bmp", "tiff", "webp", "heic",
            "cr2", "cr3", "nef", "nrw", "arw", "sr2", "raf", "dng", "orf", "rw2", "pef",
            "raw", "mos", "3fr", "erf", "kdc", "mos", "iiq", "x3f"].contains(ext) { return .image }
        if ["mp4", "mov", "avi", "mkv", "wmv", "flv", "m4v"].contains(ext) { return .video }
        if ["mp3", "aac", "wav", "flac", "m4a", "ogg", "wma"].contains(ext) { return .audio }
        if ["pdf", "doc", "docx", "rtf", "pages", "numbers", "keynote", "epub"].contains(ext) { return .document }
        if ["zip", "rar", "7z", "tar", "gz", "bz2", "xz"].contains(ext) { return .archive }

        // Code / config / text files (by extension)
        if ["swift", "c", "cpp", "h", "hpp", "m", "mm", "py", "rb", "go", "rs", "java", "kt",
            "js", "ts", "jsx", "tsx", "html", "css", "scss", "sass", "less", "json", "xml",
            "sql", "sh", "zsh", "bash", "fish", "ps1", "bat", "cmd", "awk", "sed", "tcl",
            "lua", "pl", "php", "r", "scala", "dart", "vue", "elm", "cljs", "clj", "coffee",
            "groovy", "gradle", "make", "mk", "cmake", "yml", "yaml", "toml", "ini", "cfg",
            "conf", "config", "properties", "plist", "strings", "tex", "bib", "dockerfile",
            "gitignore", "gitattributes", "gitmodules", "editorconfig", "npmrc", "yarnrc",
            "nvmrc", "node-version", "python-version", "ruby-version", "java-version",
            "tool-versions", "sdkmanrc", "env", "envrc", "env.local", "env.development",
            "env.production", "env.test", "env.example", "secrets", "credentials", "token",
            "htaccess", "htpasswd", "nginx.conf", "apache.conf", "vhost", "log", "out",
            "trace", "diff", "patch", "reg", "csv", "tsv", "svg", "graphql", "gql", "prisma",
            "proto", "thrift", "avsc", "lock", "sum", "mod", "work", "go.sum", "go.mod",
            "cargo.lock", "cargo.toml", "package-lock", "yarn.lock", "pnpm-lock", "podfile",
            "gemfile", "rakefile", "brewfile", "vagrantfile", "fastfile", "matchfile",
            "dangerfile", "jenkinsfile", "dockerfile", "docker-compose", "dockerignore",
            "npmignore", "eslintignore", "prettierignore", "gitignore", "bazelignore",
            "tf", "tfvars", "hcl", "nomad", "consul", "packer", "ansible", "playbook",
            "role", "task", "handler", "vars", "defaults", "meta", "inventory",
            "kubeconfig", "k8s", "helm", "chart", "values", "template", "ingress",
            "service", "deployment", "statefulset", "daemonset", "job", "cronjob",
            "configmap", "secret", "pvc", "pv", "rbac", "networkpolicy", "psp",
            "psp", "limitrange", "resourcequota", "hpa", "vpa", "pdb", "poddisruptionbudget"].contains(ext) { return .code }

        // Code / config files by well-known filename (no extension)
        let codeNames: Set<String> = [
            ".zshrc", ".zshenv", ".zprofile", ".zlogin", ".zlogout", ".zsh_history", ".zcompdump",
            ".bashrc", ".bash_profile", ".bash_login", ".bash_logout", ".bash_history",
            ".profile", ".inputrc",
            ".vimrc", ".gvimrc", ".viminfo", ".exrc",
            ".tmux.conf", ".screenrc",
            ".npmrc", ".yarnrc", ".nvmrc", ".node-version", ".npmignore",
            ".gitignore", ".gitattributes", ".gitconfig", ".gitmodules", ".git-credentials",
            ".editorconfig", ".dockerignore", ".eslintignore", ".prettierignore",
            ".babelrc", ".eslintrc", ".prettierrc", ".stylelintrc", ".flowconfig",
            ".graphqlrc", ".postcssrc", ".browserslistrc", ".lintstagedrc",
            ".terraformrc", ".tfvars", ".nomad", ".hcl",
            ".netrc", ".curlrc", ".wgetrc", ".wget-hsts", ".lesshst",
            ".condarc", ".piprc", ".pypirc",
            ".python-version", ".ruby-version", ".java-version", ".tool-versions", ".sdkmanrc",
            ".rspec", ".rubocop.yml", ".yardopts", ".gemrc", ".bundle", ".irbrc",
            ".bowerrc", ".jshintrc", ".jscsrc", ".jscs.json", ".tern-project",
            ".env", ".envrc", ".env.local", ".env.development", ".env.production",
            ".env.test", ".env.example", ".env.sample", ".env.template", ".env.vault",
            ".secrets", ".credentials", ".token", ".key", ".pem", ".crt", ".cer", ".der",
            ".p12", ".pfx", ".keystore", ".jks",
            ".ovpn", ".wg", ".wireguard",
            ".ssh_config", ".ssh/config", ".ssh/authorized_keys", ".ssh/known_hosts",
            ".ssh/allowed_signers", ".ssh/revoked_keys",
            ".pgpass", ".my.cnf", ".mydumper", ".mydumper.cnf",
            ".htaccess", ".htpasswd",
            ".Xmodmap", ".Xresources", ".Xdefaults", ".xinitrc", ".xsession", ".xsessionrc",
            ".xprofile", ".xinputrc", ".selected_editor",
            "p10k.zsh", ".p10k.zsh", ".oh-my-zsh",
            ".CFUserTextEncoding", ".localized",
            "makefile", "Makefile", "GNUmakefile", "makefile.am", "makefile.in",
            "CMakeLists.txt", "CMakeCache.txt",
            "Podfile", "Cartfile", "Package.swift", " Brewfile", "Vagrantfile",
            "Fastfile", "Matchfile", "Dangerfile", "Jenkinsfile",
            "Dockerfile", "docker-compose.yml", "docker-compose.yaml", "docker-compose.override.yml",
            ".nvmrc", ".ruby-version", ".python-version", ".java-version", ".node-version",
            "Rakefile", "Gemfile", "Guardfile", "Capfile", "Thorfile", "Berksfile", "Cheffile",
            "composer.json", "composer.lock", "phpunit.xml", "phpcs.xml",
            "build.gradle", "settings.gradle", "pom.xml", "build.xml", "ivy.xml",
            "webpack.config.js", "webpack.config.ts", "rollup.config.js", "vite.config.js",
            "vite.config.ts", "astro.config.mjs", "next.config.js", "next.config.ts",
            "tailwind.config.js", "tailwind.config.ts", "postcss.config.js",
            ".clang-format", ".clang-tidy", ".astylerc",
            ".kotlinc", ".scalafmt.conf", ".sbtopts", ".jvmopts",
            ".rustfmt.toml", "rust-toolchain", "rust-toolchain.toml",
            ".flake8", ".pylintrc", "pyproject.toml", "setup.py", "setup.cfg",
            "tox.ini", "pytest.ini", ".coveragerc",
            "angular.json", ".angular-cli.json", ".nx.json",
            "project.json", "workspace.json", "tsconfig.json", "jsconfig.json",
            ".babelrc.json", ".babelrc.js", ".babelrc.cjs", ".babelrc.mjs",
            ".eslintrc.json", ".eslintrc.js", ".eslintrc.cjs", ".eslintrc.yaml", ".eslintrc.yml",
            ".prettierrc.json", ".prettierrc.js", ".prettierrc.yaml", ".prettierrc.yml",
            "cspell.json", "cspell.yaml", "cspell.yml",
            ".stylelintrc.json", ".stylelintrc.js", ".stylelintrc.yaml", ".stylelintrc.yml",
            "lerna.json", "nx.json", "turbo.json", "moon.yml", "moon.yaml",
            ".changeset", ".changeset/config.json",
            "vercel.json", "netlify.toml", "surge.json", "now.json",
            ".firebase.json", ".firebaserc", "firebase.json",
            ".aws/config", ".aws/credentials", ".azure", ".gcloud",
            ".kube/config", ".kubectl", ".k9s", ".helm",
            ".docker/config.json", ".docker/daemon.json",
            ".npmrc", ".yarnrc", ".yarnrc.yml", ".yarnrc.yaml",
            ".pnp.cjs", ".pnp.loader.mjs",
            "package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
            "Cargo.toml", "Cargo.lock", "go.mod", "go.sum",
            "requirements.txt", "Pipfile", "Pipfile.lock", "poetry.lock", "pyproject.toml",
            "Gemfile", "Gemfile.lock", "composer.json", "composer.lock",
            "mix.exs", "mix.lock", "rebar.config", "erlang.mk",
            "dune", "dune-project", "opam", "jbuild",
            "stack.yaml", "stack.yaml.lock", "cabal.project", "package.yaml",
            "project.clj", "build.boot", "deps.edn", "shadow-cljs.edn",
            "spago.dhall", "packages.dhall", "spago.yaml",
            ".csproj", ".fsproj", ".vbproj", ".sln", ".props", ".targets",
            "global.json", "Directory.Build.props", "Directory.Build.targets",
            "nuget.config", "packages.config",
            "Info.plist", "Entitlements.plist", "ExportOptions.plist",
            ".swiftlint.yml", ".swiftformat", ".swift-version",
            ".clang-format", ".clang-tidy", ".astylerc",
            "build.zig", "build.zig.zon",
            "meson.build", "meson_options.txt",
            "configure.ac", "configure.in", "autogen.sh", "Makefile.am", "Makefile.in",
            "SConstruct", "SConscript", "wscript", "waf", "jamroot", "Jamfile",
            "BUILD", "BUILD.bazel", "WORKSPACE", "WORKSPACE.bazel",
            "MODULE.bazel", "REPO.bazel", ".bazelrc", ".bazelversion",
            ".buckconfig", ".buckversion", ".watchmanconfig",
            ".arcconfig", ".arclint", ".phabricator-lint",
            ".hgignore", ".hgrc", ".svnignore", ".cvsignore", ".bzrignore", ".darcsignore",
            ".stignore", ".syncthing", ".unison",
            "Procfile", "app.json", "heroku.yml", " scalingo.json",
            "fly.toml", "render.yaml", "railway.json", "vercel.json",
            "netlify.toml", "surge.json", "firebase.json",
            ".upptimerc.yml", ".upptime.yml",
            "Caddyfile", "traefik.yml", "traefik.toml",
            "haproxy.cfg", "nginx.conf", "lighttpd.conf",
            ".zsh-theme", ".zsh_plugin", ".zsh-theme.zsh",
            ".p10k.zsh", ".powerlevel10k",
            "init.vim", "init.lua", "coc-settings.json", "dein.toml", "plug.vim",
            ".ideavimrc", ".vrapperrc", ".vsvimrc", ".amix",
            ".latexmkrc", ".indent.pro", ".astylerc", ".uncrustify.cfg",
            ".astylerc", ".clang-format", ".clang-tidy",
            ".astylerc", ".astylerc.ini", ".astylerc.json",
            "stylua.toml", ".selene.toml", ".luacheckrc",
            ".luarc.json", ".luacov", ".luacheckrc",
            ".prettierrc.toml", ".prettierrc.cjs", ".prettierrc.mjs",
            ".eslintrc.cjs", ".eslintrc.mjs",
            ".htmlhintrc", ".stylelintrc.cjs", ".stylelintrc.mjs",
            ".postcssrc.json", ".postcssrc.js", ".postcssrc.cjs", ".postcssrc.mjs",
            "svgo.config.js", "svgo.config.mjs", "svgo.config.cjs",
            ".remarkrc", ".remarkrc.js", ".remarkrc.json", ".remarkrc.yaml",
            ".textlintrc", ".markdownlintrc", ".mdlrc",
            "coffeelint.json", ".coffeelintignore",
            "tslint.json", "tslint.yaml", "tslint.yml",
            ".jshintrc", ".jshintignore", ".jscsrc", ".jscs.json",
            "codecov.yml", ".codecov", "codecov.json",
            ".coveralls.yml", ".coveragerc", "coveragerc",
            ".scrutinizer.yml", ".codeclimate.yml", ".hound.yml",
            ".deepsource.toml", ".snyk", ".snyk.json",
            "renovate.json", ".renovaterc", ".renovaterc.json",
            ".dependabot", ".dependabot.yml", ".dependabot.yaml",
            ".fossa.yml", ".fossa.yaml", ".fossa.json",
            "snyk.yaml", "snyk.yml", ".snyk.json",
            ".whitesource", ".whitesource.json", ".whitesource.xml",
            ".pre-commit-config.yaml", ".pre-commit-config.yml",
            "lefthook.yml", "lefthook.yaml", "lefthook.json",
            ".huskyrc", ".huskyrc.json", ".huskyrc.js", ".huskyrc.yaml",
            ".lintstagedrc.json", ".lintstagedrc.js", ".lintstagedrc.yaml", ".lintstagedrc.yml",
            ".commitlintrc", ".commitlintrc.json", ".commitlintrc.js", ".commitlintrc.yaml",
            "commitlint.config.js", "commitlint.config.cjs", "commitlint.config.mjs",
            ".release-it.json", ".release-it.yaml", ".release-it.yml",
            "release.config.js", "release.config.cjs", ".releaserc", ".releaserc.json",
            "semantic-release.config.js", ".semantic-release",
            "changesets.config.js", ".changesets",
            "auto.config.js", ".autorc", ".autorc.json", ".autorc.js",
            ".all-contributorsrc", ".all-contributorsrc.json",
            "cSpell.json", "cspell.json", "cspell.config.js", "cspell.config.cjs",
            "cspell.config.mjs", "cspell.config.yaml", "cspell.config.yml",
            ".wordlist.txt", ".dict", ".custom-dictionary.txt",
            "remark.config.js", "remark.config.mjs", "remark.config.cjs",
            "rehype.config.js", "rehype.config.mjs", "rehype.config.cjs",
            "mdx.config.js", "mdx.config.mjs", "mdx.config.cjs",
            ".dprint.json", "dprint.json", "dprint.config.js",
            "rome.json", "biome.json", "biome.jsonc",
            "deno.json", "deno.jsonc", "deno.lock",
            "import_map.json", "vendor-manifest.json",
            "fresh.gen.ts", "twind.config.ts", "twind.config.js",
            ".knip.json", ".knip.jsonc", "knip.config.ts", "knip.config.js",
            ".depcheckrc", ".depcheckrc.json", ".depcheckrc.js",
            "depcheck.config.js", "depcheck.config.cjs", "depcheck.config.mjs",
            ".npmcheckrc", ".npmcheckrc.json",
            ".npmpackagejsonlintrc", "npm-package-json-lint.config.js",
            ".npmpackagejsonlintrc.json", ".npmpackagejsonlintrc.js",
            ".npmpackagejsonlintrc.yaml", ".npmpackagejsonlintrc.yml",
            ".licenserc", ".licenserc.json", ".licenserc.yaml", ".licenserc.yml",
            "license-checker.config.js", "license-checker.config.json",
            ".fossa.yml", ".fossa.yaml", ".fossa.json", "fossa.config.js",
            ".snyk", ".snyk.json", "snyk.yaml", "snyk.yml",
            ".bandit", ".bandit.yaml", ".bandit.yml",
            ".pyup", ".pyup.yml", ".pyup.yaml",
            ".safety", ".safety-policy.yml", ".safety-policy.yaml",
            "trivy.yaml", "trivy.yml", ".trivyignore",
            ".checkov.yaml", ".checkov.yml", ".checkov",
            ".terrascan.yaml", ".terrascan.yml", ".terrascan",
            "tfsec.yaml", "tfsec.yml", ".tfsec",
            ".infracost", ".infracost.yml", ".infracost.yaml",
            ".atlantis.yaml", ".atlantis.yml",
            "spacelift.yaml", "spacelift.yml",
            "scaffold.yaml", "scaffold.yml",
            "skaffold.yaml", "skaffold.yml",
            "kustomization.yaml", "kustomization.yml", "Kustomization",
            "catalog-info.yaml", "catalog-info.yml",
            "mkdocs.yaml", "mkdocs.yml",
            "docusaurus.config.js", "docusaurus.config.ts",
            "gatsby-config.js", "gatsby-config.ts", "gatsby-node.js", "gatsby-browser.js",
            "gridsome.config.js", "nuxt.config.js", "nuxt.config.ts",
            "quasar.conf.js", "quasar.config.js", "quasar.config.ts",
            "svelte.config.js", "svelte.config.ts", "svelte.config.mjs",
            "rollup.config.js", "rollup.config.ts", "rollup.config.mjs",
            "vite.config.js", "vite.config.ts", "vite.config.mjs", "vite.config.cjs",
            "vitest.config.js", "vitest.config.ts", "vitest.config.mjs", "vitest.config.cjs",
            "playwright.config.js", "playwright.config.ts", "playwright.config.mjs",
            "cypress.config.js", "cypress.config.ts", "cypress.config.mjs",
            "jest.config.js", "jest.config.ts", "jest.config.mjs", "jest.config.cjs",
            "karma.conf.js", "protractor.conf.js", "nightwatch.conf.js",
            "mocha.opts", ".mocharc.json", ".mocharc.js", ".mocharc.yaml", ".mocharc.yml",
            "ava.config.js", "ava.config.mjs", "ava.config.cjs",
            "tap-snapshots", ".taprc", "tap.yml", "tap.yaml",
            "qunit.config.js", "qunit.config.json",
            ".qawolf", "qawolf.config.js",
            "testcafe.config.js", "testcafe.config.cjs", ".testcaferc.json",
            "wdio.conf.js", "wdio.conf.ts", "wdio.conf.mjs",
            "codecept.conf.js", "codecept.conf.ts",
            "nightwatch.conf.js", "nightwatch.conf.ts",
            "cucumber.js", "cucumber.yml", "cucumber.yaml",
            ".behat.yml", ".behat.yaml", "behat.yml", "behat.yaml",
            "phpunit.xml", "phpunit.xml.dist", "phpcs.xml", "phpcs.xml.dist",
            "phpmd.xml", "phpmd.xml.dist", "psalm.xml", "psalm.xml.dist",
            "infection.json", "infection.json.dist",
            ".php_cs", ".php_cs.dist", ".php_cs.cache",
            ".php-cs-fixer.php", ".php-cs-fixer.dist.php",
            "rector.php", "rector.yaml", "rector.yml",
            "phpstan.neon", "phpstan.neon.dist", "phpstan.neon.ci",
            ".psalm", ".psalm.xml", "psalm.xml",
            "phan.php", "phan.config.php", ".phan", ".phan.config.php",
            "grumphp.yml", "grumphp.yaml", "grumphp.yml.dist",
            ".phpunit.result.cache", ".phpunit-watcher.yml",
            ".vapor.yml", ".vapor.yaml", "vapor.yml", "vapor.yaml",
            "serverless.yml", "serverless.yaml", "serverless.json",
            "serverless.ts", "serverless.js",
            ".serverless", ".serverlessrc", "serverlessrc",
            "samconfig.toml", "template.yaml", "template.yml",
            "cloudformation.yaml", "cloudformation.yml", "cloudformation.json",
            "openapi.yaml", "openapi.yml", "openapi.json", "swagger.yaml", "swagger.yml", "swagger.json",
            "asyncapi.yaml", "asyncapi.yml", "asyncapi.json",
            "graphql.config.js", "graphql.config.ts", "graphql.config.mjs",
            "apollo.config.js", "apollo.config.ts",
            "relay.config.js", "relay.config.ts", "relay.config.json",
            "prisma.yml", "prisma.yaml", "schema.prisma",
            "drizzle.config.ts", "drizzle.config.js",
            "hasura.config.js", "hasura.config.ts",
            "typegen.json", "nexus.ts", "nexus.js",
            "dataconnect.yaml", "dataconnect.yml",
            ".sequelizerc", "sequelize.config.js", "sequelize.config.ts",
            "knexfile.js", "knexfile.ts", "bookshelf.config.js",
            "waterline.config.js", "sails.config.js",
            "loopbackrc", ".loopbackrc", "loopback.config.js",
            "typeorm.config.js", "typeorm.config.ts", "ormconfig.json", "ormconfig.js",
            "mikro-orm.config.js", "mikro-orm.config.ts", "mikro-orm.config.ts",
            "objection.config.js", "objection.config.ts",
            "bookshelf.config.js", "bookshelf.config.ts",
            "mongoose.config.js", "mongoose.config.ts",
            "mongo.config.js", "mongo.config.ts", "mongodb.config.js",
            "redis.conf", "redis.config.js", "redis.config.ts",
            "memcached.conf", "memcached.config.js",
            "elasticsearch.yml", "elasticsearch.yaml", "elasticsearch.config.js",
            "kibana.yml", "kibana.yaml", "kibana.config.js",
            "logstash.conf", "logstash.yml", "logstash.yaml",
            "beats.yml", "beats.yaml", "metricbeat.yml", "filebeat.yml", "heartbeat.yml",
            "apm-server.yml", "apm-server.yaml",
            "grafana.ini", "grafana.conf", "grafana.config.js",
            "prometheus.yml", "prometheus.yaml", "prometheus.config.js",
            "alertmanager.yml", "alertmanager.yaml",
            "loki.yml", "loki.yaml", "loki.config.js",
            "tempo.yml", "tempo.yaml", "tempo.config.js",
            "mimir.yml", "mimir.yaml", "mimir.config.js",
            "cortex.yml", "cortex.yaml", "cortex.config.js",
            "thanos.yml", "thanos.yaml", "thanos.config.js",
            "victoria-metrics.yml", "victoriametrics.yml",
            "influxdb.conf", "influxdb.config.js",
            "telegraf.conf", "telegraf.config.js",
            "chronograf.conf", "chronograf.config.js",
            "kapacitor.conf", "kapacitor.config.js",
            "clickhouse.yml", "clickhouse.yaml", "clickhouse.config.js",
            "arangodb.conf", "arangodb.config.js",
            "couchdb.ini", "couchdb.config.js",
            "neo4j.conf", "neo4j.config.js",
            "orientdb.config.xml", "orientdb.config.js",
            "hbase-site.xml", "hive-site.xml", "hdfs-site.xml", "mapred-site.xml", "yarn-site.xml",
            "core-site.xml", "hdfs-default.xml", "mapred-default.xml", "yarn-default.xml",
            "hadoop-env.sh", "hive-env.sh", "spark-env.sh", "kafka-env.sh",
            "zoo.cfg", "zookeeper.properties", "kafka.properties", "kafka.config.js",
            "server.properties", "broker.properties", "consumer.properties", "producer.properties",
            "connect.properties", "connect-distributed.properties", "connect-standalone.properties",
            "schema-registry.properties", "ksql-server.properties", "ksql-cli.properties",
            "control-center.properties", "rest-proxy.properties",
            "cassandra.yaml", "cassandra.config.js",
            "scylla.yaml", "scylla.config.js",
            "riak.conf", "riak.config.js",
            "couchbase.conf", "couchbase.config.js",
            "foundationdb.conf", "foundationdb.config.js",
            "tidb.toml", "tidb.config.js", "tikv.toml", "tikv.config.js", "pd.toml", "pd.config.js",
            "vitess.conf", "vitess.config.js",
            "crdb.yml", "crdb.yaml", "cockroach.yml", "cockroach.yaml",
            "cockroachdb.yml", "cockroachdb.yaml", "cockroachdb.config.js",
            "yugabytedb.yml", "yugabytedb.yaml", "yugabytedb.config.js",
            "planetscale.yml", "planetscale.yaml", "planetscale.config.js",
            "supabase.config.js", "supabase.config.ts", "supabase.toml",
            "firebase.json", ".firebaserc", "firestore.rules", "firestore.indexes.json",
            "storage.rules", "database.rules.json", "remoteconfig.template.json",
            "apphosting.yaml", "apphosting.yml", "apphosting.json",
            ".replit", "replit.nix", ".replit.nix",
            "codesandbox.json", ".codesandbox", "sandbox.config.json",
            "stackblitz.json", ".stackblitzrc",
            "glitch.json", ".glitch", ".glitch.json",
            "gitpod.yml", "gitpod.yaml", ".gitpod.yml", ".gitpod.yaml",
            "devcontainer.json", ".devcontainer.json", ".devcontainer", ".devcontainer/devcontainer.json",
            "launch.json", "tasks.json", "settings.json", "extensions.json", "keybindings.json",
            "c_cpp_properties.json", ".vscode", ".vscode/settings.json", ".vscode/launch.json",
            ".idea", ".idea/workspace.xml", ".idea/tasks.xml", ".idea/vcs.xml", ".idea/modules.xml",
            ".fleet", ".fleet/settings.json", ".fleet/run.json",
            ".nova", ".nova/Configuration.json", ".nova/Tasks.json",
            ".zed", ".zed/settings.json", ".zed/tasks.json",
            "zed.json", "zed.settings.json",
            ".cursor", ".cursor/settings.json", ".cursor/tasks.json",
            ".cursorrules", "cursor.json", "cursor.settings.json",
            ".windsurfrules", ".windsurf.json", "windsurf.config.js",
            ".claude", ".claude/settings.json", ".claude/tasks.json",
            ".continue", ".continue/config.json", ".continue/config.yaml",
            ".aider", ".aider.conf.yml", ".aider.conf.yaml",
            ".aiderignore", ".aiderignore.json",
            "cline.json", ".cline", ".cline/config.json",
            "roo.json", ".roo", ".roo/config.json",
            "supermaven.json", ".supermaven", ".supermaven/config.json",
            "copilot.json", ".copilot", ".copilot/config.json",
            "tabnine.json", ".tabnine", ".tabnine/config.json",
            "codeium.json", ".codeium", ".codeium/config.json",
            "cody.json", ".cody", ".cody/config.json",
            "sourcegraph.json", ".sourcegraph", ".sourcegraph/config.json",
            "sourcery.json", ".sourcery", ".sourcery/config.json",
            "deepcode.json", ".deepcode", ".deepcode/config.json",
            "codeql.yml", "codeql.yaml", "codeql.json",
            "semgrep.yml", "semgrep.yaml", "semgrep.json",
            "sonar-project.properties", "sonar-project.xml",
            ".sonarcloud", ".sonarcloud.properties",
            ".sonarqube", ".sonarqube.properties",
            "codacy.yml", "codacy.yaml", "codacy.json",
            "codebeat.json", "codebeat.yml", "codebeat.yaml",
            "codeclimate.yml", "codeclimate.yaml", "codeclimate.json",
            "deepsource.toml", "deepsource.yml", "deepsource.yaml",
            "lgtm.yml", "lgtm.yaml", "lgtm.json",
            "scrutinizer.yml", "scrutinizer.yaml", "scrutinizer.json",
            "coveralls.yml", "coveralls.yaml", "coveralls.json",
            "codecov.yml", "codecov.yaml", "codecov.json",
            "snyk.yml", "snyk.yaml", "snyk.json",
            "fossa.yml", "fossa.yaml", "fossa.json",
            "synk.yml", "synk.yaml", "synk.json",
            "whitesource.yml", "whitesource.yaml", "whitesource.json",
            " mend.yml", "mend.yaml", "mend.json",
            "checkmarx.yml", "checkmarx.yaml", "checkmarx.json",
            "veracode.yml", "veracode.yaml", "veracode.json",
            "blackduck.yml", "blackduck.yaml", "blackduck.json",
            "contrast.yml", "contrast.yaml", "contrast.json",
            "seeker.yml", "seeker.yaml", "seeker.json",
            "bugsnag.yml", "bugsnag.yaml", "bugsnag.json",
            "rollbar.yml", "rollbar.yaml", "rollbar.json",
            "raygun.yml", "raygun.yaml", "raygun.json",
            "sentry.yml", "sentry.yaml", "sentry.json",
            ".sentryclirc", ".sentryclirc.json",
            "airbrake.yml", "airbrake.yaml", "airbrake.json",
            "honeybadger.yml", "honeybadger.yaml", "honeybadger.json",
            "logrocket.yml", "logrocket.yaml", "logrocket.json",
            "datadog.yml", "datadog.yaml", "datadog.json",
            "newrelic.yml", "newrelic.yaml", "newrelic.json",
            "dynatrace.yml", "dynatrace.yaml", "dynatrace.json",
            "appdynamics.yml", "appdynamics.yaml", "appdynamics.json",
            "splunk.yml", "splunk.yaml", "splunk.json",
            "elastic.yml", "elastic.yaml", "elastic.json",
            "opentelemetry.yml", "opentelemetry.yaml", "opentelemetry.json",
            "otel.yml", "otel.yaml", "otel.json",
            "jaeger.yml", "jaeger.yaml", "jaeger.json",
            "zipkin.yml", "zipkin.yaml", "zipkin.json",
            "prometheus.yml", "prometheus.yaml", "prometheus.json",
            "grafana.yml", "grafana.yaml", "grafana.json",
            "loki.yml", "loki.yaml", "loki.json",
            "tempo.yml", "tempo.yaml", "tempo.json",
            "cortex.yml", "cortex.yaml", "cortex.json",
            "mimir.yml", "mimir.yaml", "mimir.json",
            "thanos.yml", "thanos.yaml", "thanos.json",
            "victoria-metrics.yml", "victoria-metrics.yaml", "victoria-metrics.json",
            "influxdb.yml", "influxdb.yaml", "influxdb.json",
            "telegraf.yml", "telegraf.yaml", "telegraf.json",
            "chronograf.yml", "chronograf.yaml", "chronograf.json",
            "kapacitor.yml", "kapacitor.yaml", "kapacitor.json",
            "honeycomb.yml", "honeycomb.yaml", "honeycomb.json",
            "lightstep.yml", "lightstep.yaml", "lightstep.json",
            "honeycomb.yml", "honeycomb.yaml", "honeycomb.json",
            "axiom.yml", "axiom.yaml", "axiom.json",
            "honeycomb.yml", "honeycomb.yaml", "honeycomb.json",
            "highlight.yml", "highlight.yaml", "highlight.json",
            "highlight.run", "highlight.config.js",
            "openreplay.yml", "openreplay.yaml", "openreplay.json",
            "posthog.yml", "posthog.yaml", "posthog.json",
            "mixpanel.yml", "mixpanel.yaml", "mixpanel.json",
            "amplitude.yml", "amplitude.yaml", "amplitude.json",
            "segment.yml", "segment.yaml", "segment.json",
            "rudderstack.yml", "rudderstack.yaml", "rudderstack.json",
            "mparticle.yml", "mparticle.yaml", "mparticle.json",
            "braze.yml", "braze.yaml", "braze.json",
            "clevertap.yml", "clevertap.yaml", "clevertap.json",
            "onesignal.yml", "onesignal.yaml", "onesignal.json",
            "customerio.yml", "customerio.yaml", "customerio.json",
            "iterable.yml", "iterable.yaml", "iterable.json",
            "airship.yml", "airship.yaml", "airship.json",
            "urbanairship.yml", "urbanairship.yaml", "urbanairship.json",
            "sendbird.yml", "sendbird.yaml", "sendbird.json",
            "pubnub.yml", "pubnub.yaml", "pubnub.json",
            "pusher.yml", "pusher.yaml", "pusher.json",
            "ably.yml", "ably.yaml", "ably.json",
            "twilio.yml", "twilio.yaml", "twilio.json",
            "vonage.yml", "vonage.yaml", "vonage.json",
            "messagebird.yml", "messagebird.yaml", "messagebird.json",
            "sendgrid.yml", "sendgrid.yaml", "sendgrid.json",
            "mailgun.yml", "mailgun.yaml", "mailgun.json",
            "mailchimp.yml", "mailchimp.yaml", "mailchimp.json",
            "mailjet.yml", "mailjet.yaml", "mailjet.json",
            "postmark.yml", "postmark.yaml", "postmark.json",
            "sparkpost.yml", "sparkpost.yaml", "sparkpost.json",
            "aws.yml", "aws.yaml", "aws.json",
            "azure.yml", "azure.yaml", "azure.json",
            "gcp.yml", "gcp.yaml", "gcp.json",
            "digitalocean.yml", "digitalocean.yaml", "digitalocean.json",
            "linode.yml", "linode.yaml", "linode.json",
            "vultr.yml", "vultr.yaml", "vultr.json",
            "hetzner.yml", "hetzner.yaml", "hetzner.json",
            "ovh.yml", "ovh.yaml", "ovh.json",
            "scaleway.yml", "scaleway.yaml", "scaleway.json",
            "upcloud.yml", "upcloud.yaml", "upcloud.json",
            "exoscale.yml", "exoscale.yaml", "exoscale.json",
            "equinix.yml", "equinix.yaml", "equinix.json",
            "packet.yml", "packet.yaml", "packet.json",
            "baremetal.yml", "baremetal.yaml", "baremetal.json",
            "proxmox.yml", "proxmox.yaml", "proxmox.json",
            "esxi.yml", "esxi.yaml", "esxi.json",
            "vmware.yml", "vmware.yaml", "vmware.json",
            "hyperv.yml", "hyperv.yaml", "hyperv.json",
            "xen.yml", "xen.yaml", "xen.json",
            "kvm.yml", "kvm.yaml", "kvm.json",
            "qemu.yml", "qemu.yaml", "qemu.json",
            "libvirt.yml", "libvirt.yaml", "libvirt.json",
            "virt-manager.yml", "virt-manager.yaml", "virt-manager.json",
            "terraform.yml", "terraform.yaml", "terraform.json",
            "pulumi.yml", "pulumi.yaml", "pulumi.json",
            "crossplane.yml", "crossplane.yaml", "crossplane.json",
            "cdktf.yml", "cdktf.yaml", "cdktf.json",
            "terragrunt.yml", "terragrunt.yaml", "terragrunt.json",
            "atlantis.yml", "atlantis.yaml", "atlantis.json",
            "spacelift.yml", "spacelift.yaml", "spacelift.json",
            "env0.yml", "env0.yaml", "env0.json",
            "scalr.yml", "scalr.yaml", "scalr.json",
            "terraform-cloud.yml", "terraform-cloud.yaml", "terraform-cloud.json",
            "tfe.yml", "tfe.yaml", "tfe.json",
            "hcp.yml", "hcp.yaml", "hcp.json",
            "waypoint.yml", "waypoint.yaml", "waypoint.json",
            "consul.yml", "consul.yaml", "consul.json",
            "vault.yml", "vault.yaml", "vault.json",
            "nomad.yml", "nomad.yaml", "nomad.json",
            "boundary.yml", "boundary.yaml", "boundary.json",
            "packer.yml", "packer.yaml", "packer.json",
            "vagrant.yml", "vagrant.yaml", "vagrant.json",
            "ansible.yml", "ansible.yaml", "ansible.json",
            "puppet.yml", "puppet.yaml", "puppet.json",
            "chef.yml", "chef.yaml", "chef.json",
            "salt.yml", "salt.yaml", "salt.json",
            "cfengine.yml", "cfengine.yaml", "cfengine.json",
            "octopus.yml", "octopus.yaml", "octopus.json",
            "teamcity.yml", "teamcity.yaml", "teamcity.json",
            "bamboo.yml", "bamboo.yaml", "bamboo.json",
            "bitrise.yml", "bitrise.yaml", "bitrise.json",
            "buildkite.yml", "buildkite.yaml", "buildkite.json",
            "circleci.yml", "circleci.yaml", "circleci.json",
            "travis.yml", "travis.yaml", "travis.json",
            "appveyor.yml", "appveyor.yaml", "appveyor.json",
            "azure-pipelines.yml", "azure-pipelines.yaml", "azure-pipelines.json",
            "jenkins.yml", "jenkins.yaml", "jenkins.json",
            "github-actions.yml", "github-actions.yaml", "github-actions.json",
            ".github", ".github/workflows", ".github/actions", ".github/dependabot.yml",
            ".github/dependabot.yaml", ".github/codeql.yml", ".github/codeql.yaml",
            ".github/semantic.yml", ".github/semantic.yaml",
            ".github/release.yml", ".github/release.yaml",
            ".github/stale.yml", ".github/stale.yaml",
            ".github/lock.yml", ".github/lock.yaml",
            ".github/no-response.yml", ".github/no-response.yaml",
            ".github/issue_template.md", ".github/pull_request_template.md",
            ".github/FUNDING.yml", ".github/FUNDING.yaml",
            ".github/SECURITY.md", ".github/CODEOWNERS", ".github/CODE_OF_CONDUCT.md",
            ".github/CONTRIBUTING.md", ".github/LICENSE", ".github/README.md",
            ".github/CHANGELOG.md", ".github/RELEASE.md", ".github/VERSION",
            ".github/labels.yml", ".github/labels.yaml", ".github/settings.yml",
            ".github/settings.yaml", ".github/renovate.json", ".github/dependabot.yml",
            ".gitlab-ci.yml", ".gitlab-ci.yaml", ".gitlab-ci.json",
            ".circleci", ".circleci/config.yml", ".circleci/config.yaml", ".circleci/config.json",
            ".travis.yml", ".travis.yaml", ".travis.json",
            ".appveyor.yml", ".appveyor.yaml", ".appveyor.json",
            ".drone.yml", ".drone.yaml", ".drone.json",
            ".buildkite", ".buildkite/pipeline.yml", ".buildkite/pipeline.yaml", ".buildkite/pipeline.json",
            "azure-pipelines.yml", "azure-pipelines.yaml", "azure-pipelines.json",
            "bitbucket-pipelines.yml", "bitbucket-pipelines.yaml", "bitbucket-pipelines.json",
            "codemagic.yaml", "codemagic.yml", "codemagic.json",
            "eas.json", "expo.yml", "expo.yaml",
            "appflow.yml", "appflow.yaml", "appflow.json",
            "ionic.yml", "ionic.yaml", "ionic.json",
            ".github", ".github/workflows", ".github/actions", ".github/dependabot.yml",
            "bitrise.yml", "bitrise.yaml", "bitrise.json",
            "buddy.yml", "buddy.yaml", "buddy.json",
            "codefresh.yml", "codefresh.yaml", "codefresh.json",
            "wercker.yml", "wercker.yaml", "wercker.json",
            "shippable.yml", "shippable.yaml", "shippable.json",
            "semaphore.yml", "semaphore.yaml", "semaphore.json",
            "snap-ci.yml", "snap-ci.yaml", "snap-ci.json",
            "solano.yml", "solano.yaml", "solano.json",
            "tddium.yml", "tddium.yaml", "tddium.json",
            "magnum-ci.yml", "magnum-ci.yaml", "magnum-ci.json",
            "coveralls.yml", "coveralls.yaml", "coveralls.json",
            "codecov.yml", "codecov.yaml", "codecov.json",
            "snyk.yml", "snyk.yaml", "snyk.json",
            "fossa.yml", "fossa.yaml", "fossa.json",
            "whitesource.yml", "whitesource.yaml", "whitesource.json",
            "mend.yml", "mend.yaml", "mend.json",
            "checkmarx.yml", "checkmarx.yaml", "checkmarx.json",
            "veracode.yml", "veracode.yaml", "veracode.json",
            "blackduck.yml", "blackduck.yaml", "blackduck.json",
            "contrast.yml", "contrast.yaml", "contrast.json",
            "seeker.yml", "seeker.yaml", "seeker.json",
            "bugsnag.yml", "bugsnag.yaml", "bugsnag.json",
            "rollbar.yml", "rollbar.yaml", "rollbar.json",
            "raygun.yml", "raygun.yaml", "raygun.json",
            "sentry.yml", "sentry.yaml", "sentry.json",
            "airbrake.yml", "airbrake.yaml", "airbrake.json",
            "honeybadger.yml", "honeybadger.yaml", "honeybadger.json",
            "logrocket.yml", "logrocket.yaml", "logrocket.json",
            "datadog.yml", "datadog.yaml", "datadog.json",
            "newrelic.yml", "newrelic.yaml", "newrelic.json",
            "dynatrace.yml", "dynatrace.yaml", "dynatrace.json",
            "appdynamics.yml", "appdynamics.yaml", "appdynamics.json",
            "splunk.yml", "splunk.yaml", "splunk.json",
            "elastic.yml", "elastic.yaml", "elastic.json",
            "opentelemetry.yml", "opentelemetry.yaml", "opentelemetry.json",
            "otel.yml", "otel.yaml", "otel.json",
            "jaeger.yml", "jaeger.yaml", "jaeger.json",
            "zipkin.yml", "zipkin.yaml", "zipkin.json",
            "prometheus.yml", "prometheus.yaml", "prometheus.json",
            "grafana.yml", "grafana.yaml", "grafana.json",
            "loki.yml", "loki.yaml", "loki.json",
            "tempo.yml", "tempo.yaml", "tempo.json",
            "cortex.yml", "cortex.yaml", "cortex.json",
            "mimir.yml", "mimir.yaml", "mimir.json",
            "thanos.yml", "thanos.yaml", "thanos.json",
            "victoria-metrics.yml", "victoria-metrics.yaml", "victoria-metrics.json",
            "influxdb.yml", "influxdb.yaml", "influxdb.json",
            "telegraf.yml", "telegraf.yaml", "telegraf.json",
            "chronograf.yml", "chronograf.yaml", "chronograf.json",
            "kapacitor.yml", "kapacitor.yaml", "kapacitor.json",
            "honeycomb.yml", "honeycomb.yaml", "honeycomb.json",
            "lightstep.yml", "lightstep.yaml", "lightstep.json",
            "axiom.yml", "axiom.yaml", "axiom.json",
            "highlight.yml", "highlight.yaml", "highlight.json",
            "highlight.run", "highlight.config.js",
            "openreplay.yml", "openreplay.yaml", "openreplay.json",
            "posthog.yml", "posthog.yaml", "posthog.json",
            "mixpanel.yml", "mixpanel.yaml", "mixpanel.json",
            "amplitude.yml", "amplitude.yaml", "amplitude.json",
            "segment.yml", "segment.yaml", "segment.json",
            "rudderstack.yml", "rudderstack.yaml", "rudderstack.json",
            "mparticle.yml", "mparticle.yaml", "mparticle.json",
            "braze.yml", "braze.yaml", "braze.json",
            "clevertap.yml", "clevertap.yaml", "clevertap.json",
            "onesignal.yml", "onesignal.yaml", "onesignal.json",
            "customerio.yml", "customerio.yaml", "customerio.json",
            "iterable.yml", "iterable.yaml", "iterable.json",
            "airship.yml", "airship.yaml", "airship.json",
            "urbanairship.yml", "urbanairship.yaml", "urbanairship.json",
            "sendbird.yml", "sendbird.yaml", "sendbird.json",
            "pubnub.yml", "pubnub.yaml", "pubnub.json",
            "pusher.yml", "pusher.yaml", "pusher.json",
            "ably.yml", "ably.yaml", "ably.json",
            "twilio.yml", "twilio.yaml", "twilio.json",
            "vonage.yml", "vonage.yaml", "vonage.json",
            "messagebird.yml", "messagebird.yaml", "messagebird.json",
            "sendgrid.yml", "sendgrid.yaml", "sendgrid.json",
            "mailgun.yml", "mailgun.yaml", "mailgun.json",
            "mailchimp.yml", "mailchimp.yaml", "mailchimp.json",
            "mailjet.yml", "mailjet.yaml", "mailjet.json",
            "postmark.yml", "postmark.yaml", "postmark.json",
            "sparkpost.yml", "sparkpost.yaml", "sparkpost.json",
            "aws.yml", "aws.yaml", "aws.json",
            "azure.yml", "azure.yaml", "azure.json",
            "gcp.yml", "gcp.yaml", "gcp.json",
            "digitalocean.yml", "digitalocean.yaml", "digitalocean.json",
            "linode.yml", "linode.yaml", "linode.json",
            "vultr.yml", "vultr.yaml", "vultr.json",
            "hetzner.yml", "hetzner.yaml", "hetzner.json",
            "ovh.yml", "ovh.yaml", "ovh.json",
            "scaleway.yml", "scaleway.yaml", "scaleway.json",
            "upcloud.yml", "upcloud.yaml", "upcloud.json",
            ".npmrc", ".yarnrc", ".nvmrc", ".node-version", ".npmignore",
            ".env", ".envrc", ".env.local", ".env.development", ".env.production",
            ".env.test", ".env.example", ".env.sample", ".env.template", ".env.vault",
            ".secrets", ".credentials", ".token", ".key", ".pem", ".crt", ".cer", ".der",
            ".p12", ".pfx", ".keystore", ".jks",
            ".ovpn", ".wg", ".wireguard",
            ".ssh_config", ".ssh/config", ".ssh/authorized_keys", ".ssh/known_hosts",
            ".ssh/allowed_signers", ".ssh/revoked_keys",
            ".pgpass", ".my.cnf", ".mydumper", ".mydumper.cnf",
            ".htaccess", ".htpasswd",
            ".Xmodmap", ".Xresources", ".Xdefaults", ".xinitrc", ".xsession", ".xsessionrc",
            ".xprofile", ".xinputrc", ".selected_editor",
            "p10k.zsh", ".p10k.zsh", ".oh-my-zsh",
            ".CFUserTextEncoding", ".localized"
        ]
        if codeNames.contains(filename) { return .code }

        if url.hasDirectoryPath { return .folder }
        return .file
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(path)
    }

    static func == (lhs: SearchResult, rhs: SearchResult) -> Bool {
        lhs.path == rhs.path
    }
}
